language: node_js

node_js:
  - "5.1"

before_install:
  - sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main(install_dir='/usr/local')"

script:
  - gitbook build -v 2.6.7
  - gitbook pdf -v 2.6.7 . _book/guidelines.pdf
  - grunt deploy

env:
  global:
  - secure: "lnrr6JHJiimLu5xLNxVNdZklfWVXuUAEFzzPRT84mMR/kqI1Z24A7CnkrdIPt58lacPkLEQL341lXc+4jn+//KjbtfX173gEfU/+EFM55CO0MPv8B8PDwg4K48j/7owiz2/6j9HZnhTfOejal6Aivd0QkAYq3Ukdtn9vUPL+TbLIm3Yac/s3+qHvFy5J6wmQsJuPPhOyHdvuIKPFJsbhFHb9aKupACg41nNsV9bqZVJG1ZX/SYc5Epm2xnhUAAivHF2WS0m+hLa3OWoGK0O0alfFjJ0kVCb32leo+FvhRg5oCYGRI5497JqpWJe1OIxH/oPr1CkwMxZ07NtfZkS1KkzQnetcj9/XsrWs3FRHv1VQIXrimeGkzQ20lsEXxXH5PPK1CGaL1xkBxLzR/yybdxaUGFrpjhfGxO1d/IH0D1m4q503ay2NVh6alNhr9TSu1DdrOV2CginIwlMHpPZqQ9TMOB71HsepfcGdkfH5pMcuvs77Byykl/c6YH8PjwrVUwG80NxatEPLuwET49jHpr3W03uYRRYk//HPG/NL0iR/UCGPBLQ1aQo0Qlimlpx58YQypAwpYjLhAg2K3PMo/r4LvXDLsTw6EjB/M8uBPYiFnB4CCK1Hm4pyAJRhtOnq9t1aDr/Sbh7VtrrZyM+Zasxx+kZ8r/6aW1i8Io6NzmU="
