name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build_docs:    
    name: Build documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make check-rules > check-rule-ids.log
          make all

      - name: Get Github Token
        id: get-gh-token
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: vadeg/github-app-token-action@v0.0.1
        with:
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          application_id: ${{ secrets.APP_ID }}

      - name: Create Zally Issues
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ steps.get-gh-token.outputs.gh_access_token }}
        run: |
          scripts/create-zally-issue.sh

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
